import { writeFile, unlink, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { randomBytes } from "node:crypto";
import { spawn } from "node:child_process";
import "../server/db.mjs";
export const projectRoot = fileURLToPath(new URL("../", import.meta.url));
export async function runMysqlTool(tool, args, { input, output } = {}) {
  const runtime = join(projectRoot, ".runtime");
  await mkdir(runtime, { recursive: true });
  const credentialFile = join(
    runtime,
    `client-${randomBytes(8).toString("hex")}.ini`,
  );
  // Passwords generated by bootstrap are hex; quoted custom values are escaped for option files.
  const escape = (x) =>
    String(x)
      .replaceAll("\\", "\\\\")
      .replaceAll('"', '\\"')
      .replaceAll("\n", "\\n");
  await writeFile(
    credentialFile,
    `[client]\nhost=${process.env.DB_HOST}\nport=${process.env.DB_PORT}\nuser=${process.env.DB_ADMIN_USER}\npassword="${escape(process.env.DB_ADMIN_PASSWORD)}"\n`,
    { mode: 0o600 },
  );
  const binary = join(
    process.env.MYSQL_BASE || "C:\\Program Files\\MySQL\\MySQL Server 8.0",
    "bin",
    `${tool}.exe`,
  );
  try {
    await new Promise((resolve, reject) => {
      const child = spawn(
        binary,
        [`--defaults-extra-file=${credentialFile}`, ...args],
        { windowsHide: true, stdio: ["pipe", "pipe", "pipe"] },
      );
      let error = "";
      child.stderr.on("data", (chunk) => {
        error += chunk.toString();
      });
      child.on("error", reject);
      child.on("close", (code) =>
        code === 0
          ? resolve()
          : reject(new Error(`${tool} exited ${code}: ${error}`)),
      );
      if (output) child.stdout.pipe(output);
      else child.stdout.resume();
      if (input) input.pipe(child.stdin);
      else child.stdin.end();
      child.stdin.on("error", (e) => {
        if (e.code !== "EPIPE") reject(e);
      });
    });
  } finally {
    await unlink(credentialFile);
  }
}
